name: Build Docker Image

on:
  push:
    branches: [ master ]  # 或 main，看你分支名

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t flask-devops-app .

    - name: List built images
      run: docker images
